import 'package:flutter/widgets.dart';

import 'app_language.dart';

class AppLocalizations {
  static const Map<String, String> _az = {
    'app_name': 'Domino APP',
    'language': 'Dil',
    'language_description': 'Tətbiqin dilini seçin',
    'azerbaijani': 'Azərbaycan',
    'russian': 'Русский',
    'profile': 'Profil',
    'restaurants': 'Restoranlar',
    'inventory': 'İnventar',
    'refresh': 'Yenilə',
    'retry': 'Yenidən cəhd et',
    'login': 'Giriş',
    'register': 'Qeydiyyat',
    'username': 'İstifadəçi adı',
    'email': 'Email',
    'password': 'Şifrə',
    'confirm_password': 'Şifrəni təkrarla',
    'create_account': 'Hesab yarat',
    'login_subtitle': 'Davam etmək üçün hesabınıza daxil olun.',
    'register_subtitle': 'Oynamaq və hədiyyələri saxlamaq üçün hesab yaradın.',
    'fill_username_password': 'İstifadəçi adı və şifrəni daxil edin.',
    'enter_email': 'Email ünvanını daxil edin.',
    'server_connection_failed': 'Serverə qoşulmaq mümkün olmadı.',
    'password_min_8': 'Şifrə ən azı 8 simvoldan ibarət olmalıdır.',
    'logout': 'Hesabdan çıx',
    'my_gifts': 'Mənim hədiyyələrim',
    'inventory_bottom_menu': 'Qəbul edilmiş hədiyyələr aşağı menyuda saxlanılır',
    'received_gifts': 'Qəbul edilmiş hədiyyələr',
    'received_gifts_empty': 'Hələ qəbul edilmiş hədiyyə yoxdur',
    'received_gifts_empty_description': 'Burada yalnız digər oyunçuların sizə göndərdiyi hədiyyələr saxlanılır. Hər hədiyyənin restoranda istifadə üçün öz QR-kodu var.\n\nBaşqa oyunçulara göndərmək istədiyiniz hədiyyələr konkret restoranın kataloqunda göstərilir.',
    'gift_from': 'Göndərən: {name}',
    'gift_available': 'Aktiv',
    'gift_redeemed': 'İstifadə edilib',
    'gift_redeemed_description': 'Bu hədiyyə artıq istifadə edilib.',
    'gift_qr_description': 'Hədiyyədən istifadə edərkən bu QR-kodu restoran əməkdaşına göstərin.',
    'inventory_load_failed': 'Qəbul edilmiş hədiyyələri yükləmək mümkün olmadı.',
    'only_active_restaurants': 'Yalnız aktiv restoranlar',
    'only_available_rooms': 'Yalnız əlçatan otaqları göstər',
    'restaurants_empty': 'Uyğun restoran hələ yoxdur.',
    'backend_unavailable': 'Backend əlçatan deyil',
    'django_connection_failed': 'Django backend-ə qoşulmaq mümkün olmadı.',
    'players_online': 'Onlayn oyunçular: {count}',
    'restaurant_gifts': 'Restoran hədiyyələri',
    'create_table': 'Masa yarat',
    'open_tables': 'Açıq masalar',
    'rooms_load_failed': 'Otaqları yükləmək mümkün olmadı.',
    'rooms_load_failed_title': 'Otaqları yükləmək mümkün olmadı',
    'create_room_failed': 'Otaq yaratmaq mümkün olmadı.',
    'join_room_failed': 'Otağa daxil olmaq mümkün olmadı.',
    'room_owner_missing': 'Server otağın yaradıcısını qaytarmadı.',
    'no_open_tables': 'Hələ açıq masa yoxdur',
    'create_first_table': '2, 3 və ya 4 oyunçu üçün ilk masanı yaradın.',
    'tables_count': '{count} masa',
    'players_count': '{count} oyunçu',
    'auth_check_failed': 'Avtorizasiyanı yoxlamaq mümkün olmadı.',
    'login_again': 'Yenidən daxil ol',
    'checking_active_game': 'Aktiv oyun yoxlanılır...',
    'unfinished_game': 'Tamamlanmamış oyun var',
    'saved_table': 'Saxlanılmış masa',
    'table_number': 'Masa #{number}',
    'player_round': 'Oyunçu: {player}  ·  Raund {round}',
    'return_to_game': 'Oyuna qayıt',
    'check_again': 'Yenidən yoxla',
    'leaving': 'Çıxılır...',
    'leave_game': 'Bu oyundan çıx',
    'open_restaurants': 'Restoran siyahısını aç',
    'saved_game_note': 'Restoranları açsanız, saxlanılmış oyun silinməyəcək. Tətbiqin növbəti açılışında yenidən təklif ediləcək.',
    'saved_game_check_failed': 'Saxlanılmış oyunu yoxlamaq mümkün olmadı.',
    'saved_game_leave_failed': 'Saxlanılmış oyundan çıxmaq mümkün olmadı.',
    'restaurant_fallback': 'Restoran #{id}',
    'players': 'Oyunçular',
    'start_game': 'Oyuna başla',
    'starting_game': 'Oyun başladılır...',
    'game_start_failed': 'Oyunu başlatmaq mümkün olmadı.',
    'room_closed': 'Masa bağlandı: otaqda artıq oyunçu qalmayıb.',
    'leave_room_failed': 'Otaqdan çıxmaq mümkün olmadı.',
    'room_refresh_failed': 'Otağı yeniləmək mümkün olmadı.',
    'waiting_players': 'Oyunçular gözlənilir',
    'all_players_online': 'Bütün oyunçular onlayndır',
    'someone_offline': 'Oyunçulardan biri offline-dır',
    'realtime_connected': 'Realtime qoşulub',
    'realtime_connected_subtitle': 'Otağın vəziyyəti serverlə sinxronlaşdırılıb',
    'realtime_connecting': 'Realtime qoşulur',
    'realtime_connecting_subtitle': 'WebSocket qurulur və aktual vəziyyət alınır',
    'realtime_reconnecting': 'Yenidən qoşulur',
    'realtime_reconnecting_subtitle': 'Oyunçunun yeri saxlanılıb, vəziyyət avtomatik bərpa olunacaq',
    'realtime_disconnected': 'Realtime müvəqqəti əlçatan deyil',
    'realtime_disconnected_subtitle': 'Avtomatik olaraq yenidən qoşulmağa çalışırıq',
    'all_seats_offline': 'Bütün yerlər doludur, amma kimsə müvəqqəti offline-dır. Avtomatik yenidən qoşulmanı gözləyirik.',
    'owner_can_start': 'Bütün oyunçular onlayndır. Server paylanmasını başlatmaq olar.',
    'waiting_owner_start': 'Bütün oyunçular onlayndır. Otaq yaradıcısının oyunu başlatmasını gözləyirik.',
    'waiting_more_players': 'Daha {count} oyunçu gözləyirik.',
    'you': 'Siz',
    'owner': 'Yaradıcı',
    'empty_seat': 'Boş yer',
    'online': 'Onlayn',
    'offline': 'Offline',
  };

  static const Map<String, String> _ru = {
    'app_name': 'Domino APP',
    'language': 'Язык',
    'language_description': 'Выберите язык приложения',
    'azerbaijani': 'Azərbaycan',
    'russian': 'Русский',
    'profile': 'Профиль',
    'restaurants': 'Рестораны',
    'inventory': 'Инвентарь',
    'refresh': 'Обновить',
    'retry': 'Повторить',
    'login': 'Вход',
    'register': 'Регистрация',
    'username': 'Имя пользователя',
    'email': 'Email',
    'password': 'Пароль',
    'confirm_password': 'Повтори пароль',
    'create_account': 'Создать аккаунт',
    'login_subtitle': 'Войди в аккаунт, чтобы продолжить.',
    'register_subtitle': 'Создай аккаунт, чтобы играть и хранить подарки.',
    'fill_username_password': 'Заполни имя пользователя и пароль.',
    'enter_email': 'Укажи email.',
    'server_connection_failed': 'Не удалось подключиться к серверу.',
    'password_min_8': 'Пароль должен содержать минимум 8 символов.',
    'logout': 'Выйти из аккаунта',
    'my_gifts': 'Мои подарки',
    'inventory_bottom_menu': 'Полученные подарки доступны в нижнем меню',
    'received_gifts': 'Полученные подарки',
    'received_gifts_empty': 'Полученных подарков пока нет',
    'received_gifts_empty_description': 'Здесь хранятся только подарки, которые тебе отправили другие игроки. У каждого — свой QR-код для использования в ресторане.\n\nПодарки, подготовленные тобой для отправки другим игрокам, показываются только в каталоге конкретного ресторана.',
    'gift_from': 'Подарил: {name}',
    'gift_available': 'Доступен',
    'gift_redeemed': 'Использован',
    'gift_redeemed_description': 'Этот подарок уже использован.',
    'gift_qr_description': 'Покажи этот QR-код сотруднику ресторана при использовании подарка.',
    'inventory_load_failed': 'Не удалось загрузить полученные подарки.',
    'only_active_restaurants': 'Только активные рестораны',
    'only_available_rooms': 'Показывать только доступные комнаты',
    'restaurants_empty': 'Подходящих ресторанов пока нет.',
    'backend_unavailable': 'Backend недоступен',
    'django_connection_failed': 'Не удалось подключиться к Django backend.',
    'players_online': 'Игроков онлайн: {count}',
    'restaurant_gifts': 'Подарки ресторана',
    'create_table': 'Создать стол',
    'open_tables': 'Открытые столы',
    'rooms_load_failed': 'Не удалось загрузить комнаты.',
    'rooms_load_failed_title': 'Не удалось загрузить комнаты',
    'create_room_failed': 'Не удалось создать комнату.',
    'join_room_failed': 'Не удалось войти в комнату.',
    'room_owner_missing': 'Сервер не вернул создателя комнаты.',
    'no_open_tables': 'Пока нет открытых столов',
    'create_first_table': 'Создай первый стол на 2, 3 или 4 игроков.',
    'tables_count': '{count} столов',
    'players_count': '{count} игроков',
    'auth_check_failed': 'Не удалось проверить авторизацию.',
    'login_again': 'Войти заново',
    'checking_active_game': 'Проверяем активную игру...',
    'unfinished_game': 'Есть незавершённая игра',
    'saved_table': 'Сохранённый стол',
    'table_number': 'Стол #{number}',
    'player_round': 'Игрок: {player}  ·  Раунд {round}',
    'return_to_game': 'Вернуться в игру',
    'check_again': 'Проверить снова',
    'leaving': 'Выходим...',
    'leave_game': 'Выйти из этой игры',
    'open_restaurants': 'Открыть список ресторанов',
    'saved_game_note': 'Если открыть рестораны, сохранённая игра не удалится. Она снова будет предложена при следующем запуске приложения.',
    'saved_game_check_failed': 'Не удалось проверить сохранённую игру.',
    'saved_game_leave_failed': 'Не удалось выйти из сохранённой игры.',
    'restaurant_fallback': 'Ресторан #{id}',
    'players': 'Игроки',
    'start_game': 'Начать игру',
    'starting_game': 'Запускаем игру...',
    'game_start_failed': 'Не удалось запустить игру.',
    'room_closed': 'Стол закрыт: в комнате больше не осталось игроков.',
    'leave_room_failed': 'Не удалось выйти из комнаты.',
    'room_refresh_failed': 'Не удалось обновить комнату.',
    'waiting_players': 'Ожидание игроков',
    'all_players_online': 'Все игроки в сети',
    'someone_offline': 'Кто-то из игроков offline',
    'realtime_connected': 'Realtime подключён',
    'realtime_connected_subtitle': 'Состояние комнаты синхронизировано с сервером',
    'realtime_connecting': 'Подключаем realtime',
    'realtime_connecting_subtitle': 'Устанавливаем WebSocket и получаем актуальное состояние',
    'realtime_reconnecting': 'Переподключаемся',
    'realtime_reconnecting_subtitle': 'Место игрока сохранено, состояние восстановится автоматически',
    'realtime_disconnected': 'Realtime временно недоступен',
    'realtime_disconnected_subtitle': 'Пробуем подключиться снова автоматически',
    'all_seats_offline': 'Все места заняты, но кто-то временно offline. Ждём автоматическое переподключение.',
    'owner_can_start': 'Все игроки в сети. Можно запускать серверную раздачу.',
    'waiting_owner_start': 'Все игроки в сети. Ожидаем запуск от создателя комнаты.',
    'waiting_more_players': 'Ожидаем ещё {count} игрока(ов).',
    'you': 'Ты',
    'owner': 'Создатель',
    'empty_seat': 'Свободное место',
    'online': 'Онлайн',
    'offline': 'Offline',
  };

  static String translate(
    AppLanguage language,
    String key, {
    Map<String, Object?> arguments = const {},
  }) {
    final translations = language == AppLanguage.az ? _az : _ru;
    var value = translations[key] ?? _ru[key] ?? key;

    for (final entry in arguments.entries) {
      value = value.replaceAll('{${entry.key}}', '${entry.value ?? ''}');
    }

    return value;
  }
}

extension AppLocalizationContext on BuildContext {
  AppLanguage get appLanguage => LanguageScope.of(this).language;

  String tr(
    String key, {
    Map<String, Object?> arguments = const {},
  }) {
    return AppLocalizations.translate(
      appLanguage,
      key,
      arguments: arguments,
    );
  }
}
